[UPGRADE] version 0.19.0 stable
CodiTramuntana/decidim-fapac-app pull request #5
Opened 2019-11-15 10:02 UTC by danict93

Solves basecamp's: https://3.basecamp.com/4186608/buckets/12708820/todos/2143771617

Upgraded to version 0.19.0 stable.

2019-11-22 14:47 UTC, aitorlb requested changes
Update `decidim` gem again to include latest bugfixes in `0.19-stable` branch

2019-11-22 14:58 UTC, aitorlb commented on Gemfile
>  # We are pointing to this branch, because we need the new developments of the branch
```suggestion
```

2019-11-22 15:00 UTC, aitorlb commented on Gemfile
>  # We are pointing to this branch, because we need the new developments of the branch
Remove these comments, please :point_up_2:

2019-11-25 08:57 UTC, victorol1 commented on Gemfile
>  # We are pointing to this branch, because we need the new developments of the branch
Done

2019-11-25 08:57 UTC, victorol1 commented
> Update `decidim` gem again to include latest bugfixes in `0.19-stable` branch

Done!

2019-12-09 10:28 UTC, merged